# Site settings
title: HackLand
email: info@aucklandhackspace.nz
url: https://aucklandhackspace.nz
description: "A nest of tech, art, creativity and freedom"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: HackLand.nz

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AucklandHackspace
  - title: facebook
    url: https://facebook.com/AuckHackspace/
  - title: github
    url: https://github.com/HakLand/

# Build settings
markdown: kramdown
permalink: pretty
