# Site settings
title: Hackland - A hakerspace in Auckland
email: info@aucklandhackspace.nz
url: http://hackland.nz/
description: "A nest of tech, art, creativity and freedom.  Hackland is a makerspace/hakerspace/public workshop situated in Kingsland Auckland."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: HackLand.nz

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://join.slack.com/t/hakland/shared_invite/zt-2fqramvm-UY8p_R49~Q1EKQfYgzcjKA
  - title: github
    url: https://github.com/HakLand/
  - title: twitter
    url: https://twitter.com/AKL_Hackspace/
  - title: facebook
    url: https://facebook.com/AuckHackspace/

# Build settings
markdown: kramdown
permalink: pretty
